### ISSUE TITLE
stm32-hal and stm32f4-smoltcp

### ISSUE THREAD

**Issue by jordens** [m-labs/adc2tcp#1]
Can we move the the embedded-hal layers early?
https://github.com/stm32-rs/stm32f4xx-hal

And are there any obstacles to using the existing hal based stm32-smoltcp crate instead? Or merging yours with this one? AFAICT they address the exact same use case.
https://github.com/adamgreig/stm32f4-smoltcp

**Comment by astro** [comment]
I wasn't aware of the latter. Thank you for the links!

**Comment by astro** [comment]
How much do you prefer `stm32f4-smoltcp`? My `stm32-eth` is a tad more structured and can be ported to the `stm32f4` device crate.

**Comment by jordens** [comment]
In the end I don't care at all as long as the best crate stack with the best long term survival chance/support/activity is chosen. If you can make the argument that your stack is the better one I am happy.
If you agree that rebasing onto `stm32f4-hal` is good and integrate the Ethernet HAL stuff into `stm32*-hal`, is there a chance that the remaining "structuredness" in `stm32-eth` can be applied to/merged with `stm32f4-smoltcp` to arrive at a single stack? Or would there still be a need to have two different crates that put smoltcp on `stm32f4-hal`?

**Comment by astro** [comment]
I have transferred `stm32-eth` to the **stm32-rs** organization for greater visibility. There I hope it will attract more contributions to become the go-to Ethernet driver for STM32F* controllers.

**Comment by jordens** [comment]
Good! Thanks.
What's the plan w.r.t. [stm32f4-smoltcp](https://github.com/adamgreig/stm32f4-smoltcp)? Develop in parallel, compete, and see which wins?

**Comment by astro** [comment]
The author told me he is happy to have it replaced by `stm32-eth`.
